# Generated by Django 3.2.9 on 2021-11-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campos',
            name='tipo_noticia',
            field=models.CharField(default=1234, max_length=250),
            preserve_default=False,
        ),
    ]
