# Generated by Django 3.2.9 on 2021-11-10 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campos', '0003_auto_20211110_0858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autores',
            old_name='autor_materia',
            new_name='nome_autor',
        ),
        migrations.AddField(
            model_name='campos',
            name='autor_materia',
            field=models.ManyToManyField(to='campos.Autores'),
        ),
    ]
