# Generated by Django 3.2.9 on 2021-11-04 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campos', '0003_auto_20211104_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campos',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/'),
        ),
    ]
