# Generated by Django 3.2.9 on 2021-11-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campos', '0004_alter_campos_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='campos',
            name='autor_materia',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='campos',
            name='cidade_autor',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='campos',
            name='descricao',
            field=models.TextField(max_length=4000, null=True),
        ),
        migrations.AddField(
            model_name='campos',
            name='imagem_autor',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/'),
        ),
        migrations.AddField(
            model_name='campos',
            name='legenda_foto',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
