# Generated by Django 3.2.9 on 2021-11-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campos', '0005_auto_20211110_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='campos',
            name='visualizacoes',
            field=models.IntegerField(default=0),
        ),
    ]
