# Generated by Django 3.2.9 on 2021-11-06 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campos', '0005_auto_20211106_0830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campos',
            name='imagemheight',
        ),
        migrations.RemoveField(
            model_name='campos',
            name='imagemwidth',
        ),
    ]
