# Generated by Django 3.2.9 on 2021-11-06 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campos', '0006_auto_20211106_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='campos',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
